### ISSUE TITLE
关于图像分块的问题

### ISSUE THREAD

**Issue by krmui** [LunarShen/SECRET#3]
请问一下论文中的add a lightweight bottleneck on top of the feature map f to produce f′, and then horizontally split f′ into two parts.，用一个轻量级的bottleneck生成特征f‘，再将特征分为两个部分，这个操作仅仅是将图像分块吗，这和直接将全局图像的特征分为上下两个部分相比的优势在哪？主要是对这个轻量级的bottleneck作用不是很清楚，希望能得到您的解答

**Comment by LunarShen** [comment]
The added bottleneck achieves better local features than without it, which is a trick in training.
The bottleneck can be discarded if only global features are used for inference.
