### ISSUE TITLE
 fully unsupervised re-id

### ISSUE THREAD

**Issue by Sunshine19980919** [LunarShen/SECRET#4]
Hello, author! Thank you for your outstanding work!

I would like to ask: 
If I want to“SECRET "applies to fully unsupervised re-id. How should I set the command to get started quickly?

**Comment by luluaa** [comment]
Hello! Thanks for your great work. I would like to ask if the unsupervised setting is to comment out the code about loading pre-training model on source domain (my understanding), but the mAP I run on the market is only 32, and the mAP on the duke is 42. Do you know where the problem is?

**Comment by LunarShen** [comment]
@Sunshine19980919 On the fully unsupervised setting, you could just skip the first pre-training stage and run the fine-tuning stage with only the ImageNet-pretrain weights. 
@luluaa you could try to load ImageNet-pretrain weights instead of commenting out the related code.
